defmodule MyGroupCollectRegister.Repo.Migrations.CreateTablePassengers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:passengers, primary_key: false) do
      add :passenger_id, :uuid, null: false, primary_key: true
      add :trip_id, :uuid, null: false
      add :account_id, :uuid, null: false
      add :first_name, :text, null: false
      add :middle_name_or_initial, :text
      add :last_name, :text, null: false
      add :preferred_name, :text
      add :phone_number, :text
      add :date_of_birth, :date, null: false
      add :gender, :text, null: false
    end
  end

  def down do
    drop table(:passengers)
  end
end
